name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

env:
  ACTIONS_STEP_DEBUG: true
  ACTIONS_RUNNER_DEBUG: true

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Update Logo
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "(?i)<CImage className=\"sidebar-brand-full mt-3\" src=\\{i\\}"
          replace: "<CImage className=\"sidebar-brand-full mt-3\" src=\"https://optekwebstorage.blob.core.windows.net/repository/logo_cipp.png\""
          include: "src/components/layout/AppSidebar.jsx"
          regex: true
      - name: Update CSS Themes
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "$cyberdrain-primary: #219c94;"
          replace: "$cyberdrain-primary: #219c94;"
          include: "src/scss/*"
          regex: false		  
      - name: Update Footer
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "<CFooter(.*)<\/CFooter>"
          replace: "<CFooter></CFooter>"
          include: "src/components/layout/AppFooter.jsx"
          regex: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_BAY_00192C110 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_BAY_00192C110 }}
          action: "close"
